image: softartdev/android-fastlane

stages:
  - build
  - test
  - staging

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

# Check linting
lintDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  only:
    - develop

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
  only:
    - develop

# Run all tests, if any fails, interrupt the pipeline(fail it)
debugTests:
  interruptible: true
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
  only:
    - develop

# Deploy on Firebase Distribution via Fastlane (staging environment)
deployStaging:
  stage: staging
  script:
    - touch "gitlab-ci.properties"
    - echo "FIREBASE_APP_ID=${FIREBASE_APP_ID}" > gitlab-ci.properties
    - echo "FIREBASE_CLI_TOKEN=${FIREBASE_CLI_TOKEN}" >> gitlab-ci.properties
    - fastlane distribute
  environment:
    name: staging
  only:
    - develop