# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end

    desc "Submit a new beta build to Firebase App Distribution"
    lane :distribute do
        build_android_app(
            task: "assemble",
            build_type: "debug"
        )
        firebaseAppId = get_properties_value(
            key: "FIREBASE_APP_ID",
            path: "./gitlab-ci.properties"
        )
        firebaseCLIToken = get_properties_value(
           key: "FIREBASE_CLI_TOKEN",
           path: "./gitlab-ci.properties"
        )
        firebase_app_distribution(
            app: firebaseAppId,
            testers: "stefano.bitto.dev@gmail.com",
            firebase_cli_token: firebaseCLIToken,
            release_notes_file: "./fastlane/release-notes.txt"
        )
    end
end